### ISSUE TITLE
Ignore line length in block strings?

### ISSUE THREAD

**Issue by daurnimator** [mpeterv/luacheck#100]
I would like to have a way to ignore the line length check inside of block strings and comments.
I often have quotes from things that I don't want to snip the length of.
Also sometimes I have long urls that by themselves exceed the line limit.

**Comment by mpeterv** [comment]
Should this also affect lines with normal string literals like `local foo = "long long long..."`?

**Comment by daurnimator** [comment]
Maybe?
I did run into that for some particularly long error messages.

Though I feel like others will disagree

**Comment by mpeterv** [comment]
Okay, so I think that the way to do this is to add versions of 'max_line_length' options specifically for lines inside comments and long strings. E.g. 'max_comment_line_length' and 'max_string_line_length'. Then it would be possible to set different length limits for different types of lines or disable limits entirely, selectively. On top of that warning codes could become different based on line type, like for trailing whitespace warnings. But that would be breaking change for those who use 'ignore 631' to get rid of the warning.
