### ISSUE TITLE
Global configuration file

### ISSUE THREAD

**Issue by mpeterv** [mpeterv/luacheck#102]
There should be a way to put some configuration into a file in predetermined location and have it apply when project-specific config isn't found.

Some points:

* Why not use global config even when local config is found, as a foundation? The problem is that then presence of local config doesn't ensure consistent behaviour for several users as well as it does now (currently it's enough to set 'std' option or use same Lua version).
* What should be the name of the file? '.luacheckrc' most likely, like local config.
* Where should the file be located? It has to depend on OS, need to check what's typically used on Windows.
* Should there be options to disable or alter path of global config? An option to disable it should be enough.

**Comment by Positive07** [comment]
I would like to standarize the configuration file used in `.luacheckrc` and possibly merge it with [atom-autocomplete-lua `.luacompleterc`](https://github.com/dapetcu21/atom-autocomplete-lua/#configuration)

@mpeterv do you have any interest on this? What about you @dapetcu21?

**Comment by mpeterv** [comment]
@Positive07 that could be interesting, but please open a separate issue for it.

**Comment by Positive07** [comment]
If you are fine with discussing in this repo I'll do it, otherwise I think we can discuss it privately (I still need to see if @dapetcu21 is interested too)

**Comment by dapetcu21** [comment]
@Positive07 Could be interesting, but it's a pretty big undertaking, both in terms of coordination effort and actual development.

**Comment by Positive07** [comment]
All right lets discuss this over at Positive07/.luarc#1

**Comment by mpeterv** [comment]
Implemented on master branch, global config location is `%USERPROFILE%\Local Settings\Application Data\Luacheck\Config\.luacheckrc` on Windows and `$XDG_CONFIG_HOME/luacheck/.luacheckrc` or `~/.config/luacheck/.luacheckrc` on other systems (by default). Need to check if there are better options for Windows and Mac.

**Comment by Positive07** [comment]
A few options, the install folder, next to luajit... Also why `Luacheck\Config` in Windows and not simply `Luacheck`?

**Comment by mpeterv** [comment]
Yes, just `Luacheck` for Windows is good enough. I don't want to use intallation directory of Lua/LuaRocks or Luacheck itself, it should be a single location. Otherwise user would have to copy files around if using several installations (e,g. with hererocks).

**Comment by Positive07** [comment]
Understood, sounds great then!

**Comment by mpeterv** [comment]
Yes, I plan to make a new release tomorrow

**Comment by mpeterv** [comment]
I'm uncertain if on Mac config should be under `~/.config` like on Linux or under `~/Library/Application Support` as recommended by [Mac app programming guide](https://developer.apple.com/library/content/documentation/General/Conceptual/MOSXAppProgrammingGuide/AppRuntime/AppRuntime.html).

**Comment by mpeterv** [comment]
After reading https://github.com/Microsoft/vscode/issues/3884 looks like `~/Library/Application Support` is preferred.
