### ISSUE TITLE
Q: Вопрос - в ветке master Git-c3729be куда-то пропал ./Src/luacheck/stds.lua а он нужен?

### ISSUE THREAD

**Issue by VictorVG** [mpeterv/luacheck#109]
Собственно вопрос - в ветке master _Git-c3729be_ куда-то пропал ./Src/luacheck/stds.lua а он нужен? Я просмотрел историю коммитов по веткам master и DEV но момента его удаления не зафиксировал, потому у меня и возник вопрос о необходимости данного модуля.

**Comment by mpeterv** [comment]
Нет, не нужен, он был убран в 0.19.0 (a9e2e36).

**Comment by VictorVG** [comment]
Ясно, значит и у себя удалю. Спасибо!
