### ISSUE TITLE
.luacheck std doesn't override cli --std

### ISSUE THREAD

**Issue by Positive07** [mpeterv/luacheck#110]
As reported in AtomLinter/linter-luacheck#32 the `.luacheckrc` file `std` config should override the `--std` argument passed in the CLI, or be added together, but currently the CLI takes presedence and the `.luacheckrc` `std` option is totally ignored.

I always thought that Luacheck had the following hierarchy:
* CLI
* `.luacheckrc`
* Inline

So inline is more important than the `.luacheclrc` file, and the CLI. And the `.luacheckrc` files is more important than the CLI. This is not actually specified anywhere, but could be deduced from the structure of the docs... is this supposition wrong or is the issue described valid?

**Comment by mpeterv** [comment]
Current behaviour is intended, somehow I missed documenting it, I'm sorry about that. The idea is that CLI options allow one to tweak configuration without having to go and edit `.luacheckrc`. It also allows tools to ensure value of some options regardless of what is specified in the config. E.g. a lot of editor plugins  use `--formatter <formatter>` and then rely on the formatter passed through CLI being used.

It would be more convenient for your usecase if config overwrote CLI, but I think that once default config is implemented (#102) there will be no point in editor-specific configuration and this will not be an issue.

**Comment by Positive07** [comment]
I understand and that seems fine, documenting this behaviour and implementing the global config should definitely fix the issue.

Other possible fix would be for tools to be able to specify a default config (separate from that of the CLI) and that could be overwritten by `.luacheckrc`
