### ISSUE TITLE
ignore the "unused variable length argument"

### ISSUE THREAD

**Issue by hchow77** [mpeterv/luacheck#112]
Noticed a case where I have a variable length argument function, however I am not using the argument in my function. I have been using the ignore pattern noted in #40 so I can maintain context on my unused parameters if I mark them like that, but as "_..." does not work, seems that I may want to ignore them separately in my case.

That said, I noticed the code for "unused variable length argument" was actually the same as the normal "unused argument" code (212), and I wanted to avoid turning off 212 altogether, so figured perhaps making the "unused variable length argument" a separate code would potentially be reasonable.

Also tried ignoring "..." (literally at first, forgot this was regex, but "\\.\\.\\." didn't seem to work either), which would suffice, especially if changing the code is something you wanted to avoid. If there's an ignore pattern that can get that for me, great, but otherwise maybe an update so that it is ignorable would be reasonable.

Thanks for the consideration.

**Comment by mpeterv** [comment]
In Lua patterns special characters are escaped using `%`, not `\\`. `--ignore 212/%.%.%.` works. Alternatively, you can replace  the vararg with a named argument since it's unused anyway, e.g. `_other_arguments`.

**Comment by hchow77** [comment]
Nice. That pattern worked perfectly. Forgot about the `%` in regex bit. Thanks a lot!
