### ISSUE TITLE
Request: init.lua

### ISSUE THREAD

**Issue by andrewstarks** [mpeterv/luacheck#12]
This is such a small and trivial request, and also one that is mostly about opinion:

renaming `.\luacheck.lua` to `.\luacheck/init.lua` makes manual installation (especially dealing with deployment systems that make recursion somewhat painful... ie nuget/coapp) easier.

Feel free to ignore this, but I thought I'd throw it out. Thanks!

**Comment by mpeterv** [comment]
No problem, I'll do this.

**Comment by mpeterv** [comment]
How exactly are you installing manually? I'd like to add a section about that in the documentation since it is reported to be a difficult thing.

**Comment by andrewstarks** [comment]
My apologies for not responding more quickly. 

The windows issue is that the luacheck.lua file cannot be run from the command line as `luacheck.lua <args>` and instead needs to be `lua luacheck.lua ...`. I'll whip up a bat wrapper and summit a pull request, after I verify that there are no other issues.

Thank you for your quick response!

**Comment by mpeterv** [comment]
I see. I may have misunderstood you then: there were two files called `luacheck.lua`, one in `bin` and one in `src` (`luacheck` module). I have renamed the latter to `src/luacheck/init.lua`, but perhaps you meant the former?

A pull request would be most welcome!

**Comment by andrewstarks** [comment]
You understood it correctly. I was not speaking to any "Windows" issue.
Only to a very minor point, which was that the module files are slightly
easier to manage, when they are all in one directory.

The `luacheck.lua` file that is meant to be run from the command line
speaks to the lual issue that was raised, which is that Sublime-linter
can't run it in Windows because it won't execute... AT LEAST i think that
is the case. I had a meeting and am only now getting to test it out...

I'll let you know and hopefully soon. Thanks!
