### ISSUE TITLE
ansicolor causes `attempt to call a table value` error

### ISSUE THREAD

**Issue by andrewstarks** [mpeterv/luacheck#13]
Windows 7 / lua / command line:

```
lua luacheck.lua --no-color myfile.lua
--> output works as expected
lua luacheck.lua myfile.lua
--[[-->
Fatal error: Luacheck 0.7.3 bug (please report at github.com/mpeterv/luacheck/issues):
...drew\src\mediacircus\x64\Release\lua\luacheck\format.lua:52: attempt to call a table value (upvalue 'ansicolors')
stack traceback:
        ...drew\src\mediacircus\x64\Release\lua\luacheck\format.lua:52: in upvalue 'format_color'
        ...drew\src\mediacircus\x64\Release\lua\luacheck\format.lua:76: in upvalue 'format_file_report_header'
        ...drew\src\mediacircus\x64\Release\lua\luacheck\format.lua:83: in function <...drew\src\mediacircus\x64\Release\lua\luacheck\format.lua:82>
        ...drew\src\mediacircus\x64\Release\lua\luacheck\format.lua:116: in function 'luacheck.format'
        x64\Release\luacheck.lua:279: in function <x64\Release\luacheck.lua:14>
        [C]: in function 'xpcall'
        x64\Release\luacheck.lua:294: in main chunk
        [C]: in ?
--]]
```

It appears that ansicolor may have changed for you, although I may have the wrong version. I'll check that now.

Also, ansicolors appears to be abandon-ware, replaced by https://github.com/hoelzro/lua-term, and it all looks like spewed garbage in windows. I'm not sure, but I think that lua-term works with windows.... i'm probably wrong about that...

Anyway, I suggest:

1: Disabling color output as the default behavior
2: Make ansicolor / lua-term an optional dependency, given that it doesn't add anything to the capability and many will appreciate not having to install it (those of us that can't use luarocks)

I will use the configuration feature or my yet to be written batch file to disable this, so nor harm and no foul.

Your work is much appreciated. This is an extremely helpful tool.

**Comment by mpeterv** [comment]
I would like to avoid lua-term as it requires compilation (it has a part written in C). Anyway, there is a maintained fork of ansicolors (https://github.com/kikito/ansicolors.lua) which has the issues fixed. In particular, it doesn't color output if the terminal doesn't support colors, as it often is on Windows.

I plan to partially embed ansicolors into luacheck in 0.8.0 with some changes as I want to fall back to quoting variable names when coloring isn't supported, and that flag isn't exported in ansicolors interface. IMO after that there wouldn't be many reasons to disable coloring by default.

**Comment by andrewstarks** [comment]
Ahh! Thank you for that link! 

On windows, ansicolors does nothing. So, it's a pain to need to install it when you're not using luarocks. However, busted needs it too, so.... meh. it's already there.

Upshot: I used the link that you sent me and it worked beautifully.

This is a feature request, but I understand if you think it's a bad idea. It would require you to test a "don't have it" and "do have it" version, which adds complexity.

Please feel free to close this out and again, thank you!

**Comment by mpeterv** [comment]
No problem, thank you for feedback! I _do_ plan to implement the second point. I will close this when I remove dependency on ansicolors in master branch. Testing both cases manually would indeed be painful, but it is easy enough to set up automatically on travis-ci.
