### ISSUE TITLE
Wrong field detection

### ISSUE THREAD

**Issue by johnd0e** [mpeterv/luacheck#132]
Sample code (artifical):
`table.insert:find()`

Luacheck report:
`(W143) accessing undefined field 'insert.find' of global 'table'`

As you can see `find` is not meant to be `table.insert` field, so I suppose the report is false.

Edit:
Perhaps sample is not good.
In real code I have `Object.Title:find"menu.+»"`, where `Title`-property is returned by `Object`-metamethod `__index`, but this implementation is out of source (so `Object.Title` is just defined as global in custom std set)

**Comment by mpeterv** [comment]
If `a.b:c()` is valid then `a.b.c` exists, and if `a` is a global, luacheck will warn about the whole `a.b.c` as  a field. This means that if there are strings or other objects with methods stored in fields of globals, their methods should be listed in your custom std set.

**Comment by johnd0e** [comment]
Thank you!
