### ISSUE TITLE
How can I disable the luacheck if the lua file is large?

### ISSUE THREAD

**Issue by membphis** [mpeterv/luacheck#133]
In my project, the lua file is too large, it's about 3-5mb(it's generated by machine).

when I open it (visual code), it'll cause high CPU load.

can we skip lua check if the lua file is large? How to do this?

**Comment by mpeterv** [comment]
If you don't have it already, create luacheck config in the root directory of your project (file named `.luacheckrc`). Then put `exclude_files` option into the config file to disable checking for the large file: `exclude_files = {"path_to_large_file.lua"}`. If the visual code extension you are using is implemented correctly it should work.

**Comment by mpeterv** [comment]
@membphis does my answer solve your problem?
