### ISSUE TITLE
Wish for Luacheck module: prev_line in case of E011

### ISSUE THREAD

**Issue by johnd0e** [mpeterv/luacheck#134]
```
print(function()end
if ...
```
This sample produces error 011: `expected ')' (to close '(' on line 1) near 'if'`
The error is on line 2 but refers to line 1

It would be nice, if luacheck report also contained `prev_line`/`prev_column` fields.

**Comment by mpeterv** [comment]
Implemented on master branch, `prev_column` and `prev_end_column` fields are added as well for ease of highlighting related column ranges.
