### ISSUE TITLE
Best way to approach luacheck support for nginx.conf files

### ISSUE THREAD

**Issue by kostyay** [mpeterv/luacheck#145]
Hi
We use nginx openresty with lua support in our project.
Basically this allows me to use lua code in specific blocks defined inside of nginx.conf file.
For example:
```
log_by_lua_block { require("logger").log_stuff() }
content_by_lua_block { ... }
init_by_lua_block { .. }
```
There are a bunch more `*_by_lua_block` directives that can be used that contain regular lua code.
I would like to run luachecker on all of them to detect possible errors. 
I could write a script that would extract all the lua blocks to a file and then run luachecker on each one of them, but personally I would prefer to interface with luachecker and perhaps write a custom parser for it to look only at the *lua_block stuff.
Cheers

**Comment by mpeterv** [comment]
Hi,

I'm not sure that luacheck itself should be able to parse and check nginx.conf files, it's a bit of feature bloating.

You could write a Lua script to extract the Lua blocks and check them using `luacheck.check_strings()` function from the public luacheck module, and then format warning messages using `luacheck.get_message()`. See [luacheck module docs](https://luacheck.readthedocs.io/en/stable/module.html).

**Comment by kostyay** [comment]
Thanks, I will do that!
