### ISSUE TITLE
Invalid escape sequences

### ISSUE THREAD

**Issue by Resike** [mpeterv/luacheck#152]
Invalid escape sequences should be warnings instead of errors, since the file still can be compiled regardless.

**Comment by rubo77** [comment]
Couldnt regular expressions be treated as correct at least?

we get 


     (E011) invalid escape sequence '\$'

at

     if string.match(value, "^\$%d\$.*") then

**Comment by hugomg** [comment]
@rubo77, your code is actually wrong though. The Lua interpreter produces a syntax error saying `invalid escape sequence near '"^\$'` when it attempts to evaluate that piece of code.

Syntactly speaking, all Lua string literals are treated the same, no mater whether they are intended to be used as Lua patterns, regex patterns for an external library, or just a regular old string.

If you want to use Lua pattern matching functions like `string.match`, the escape character is `%`. So to match a digit surrounded by dollar signs you should use `"^%$%d%$.*"`

If you are using an external regex library with PCRE syntax, where the escape character is the backslash, then you need to escape the backslash inside the Lua string literal, just like you would have to do in any other language that doesn't have special syntax for regular expression literals. That is, you would need to use `"^\\$\\d\\$.*"`
