### ISSUE TITLE
Inline options please.

### ISSUE THREAD

**Issue by xpol** [mpeterv/luacheck#16]
It would be nice to have an inline options for luacheck.

Something lile:

~~~~Lua
function test:fun() -- [luacheck-unused: self]
   print(jit.version) -- [luacheck-globals: jit]
end

function test:fun2() -- still get warned here...
   print(jit.version) -- still get warned here...
end
~~~~

This is very useful because:
1. self here in test:fun() may be required by some other framework but I don't use it.
2. jit maybe only get use once here I don't want add it to command line options of config file.

**Comment by mpeterv** [comment]
I agree that this would be very useful. I plan to implement this in 0.9.0 version (0.8.0 release is coming this/next week).

I'm thinking of syntax `-- luacheck: ignore foo bar, globals baz`: `luacheck:` marks comment as inline option, and then there go comma separated options with space separated arguments. Inline option will apply till the end of the innermost function, precise control can be done using `enable` option. Additionally, if there is code on the line of inline option, it will only affect that line. E.g.

```lua
foo() -- reported
-- luacheck: ignore foo
foo() -- ignored
-- luacheck: enable foo
foo() -- reported
foo() -- luacheck: ignore foo -- ignored
```

**Comment by xpol** [comment]
@mpeterv That syntax is great!

**Comment by mpeterv** [comment]
@xpol I've implemented inline options on inline_options branch, you can test it like this: `git clone https://github.com/mpeterv/luacheck && cd luacheck && git checkout inline_options && sudo luarocks make rockspecs/luacheck-scm-9.rockspec`. Not all options are implemented yet and it is not very well tested, but I plan to include it in next release later this week.

**Comment by xpol** [comment]
It works. Thanks @mpeterv !
