### ISSUE TITLE
Catch for loops counting up when they should be counting down

### ISSUE THREAD

**Issue by Zash** [mpeterv/luacheck#160]
Consider a for loop like this:

``` lua
for i = #a, 1 do
  something(i)
end
```

This is very likely a mistake, and the intention was to iterate down over some array, ie:

``` lua
for i = #a, 1, -1 do
  something(i)
end
```

Is this something luacheck can or should point out?

**Comment by mpeterv** [comment]
This sounds helpful, I've made mistakes like that one, should be easy to implement, too, just go through the AST recursively looking for `ForNum` nodes with limits like that. Just need to figure out the warning code. Probably something in `5xx`.

**Comment by mpeterv** [comment]
Implemented on master branch.
