### ISSUE TITLE
Windows argument escaping fails with spaces

### ISSUE THREAD

**Issue by SquidDev** [mpeterv/luacheck#169]
Apologies for weird Windows specific bugs:

`luacheck.lua_fs.quote_arg` will wrap paths with spaces in them in quotes _before_ escaping special characters. This means a path like `C:\foo bar` is escaped into `^"C:\foo bar^"` rather than `"C:\foo bar"`.

This was causing `get_mode` to fail as it considered the path as two arguments (`"C:\foo` and `bar"`) rather than one complete one.

Putting the character escape before the quoting appeared to fix this problem, though I haven't tested this especially thoroughly so may cause other issues. I'm happy to provide any more information if needed :).

**Comment by mpeterv** [comment]
Thanks for the report! Windows is supposed to be supported just as well as other systems.

That quoting code was tested by round-tripping random strings through a program that echoes its arguments, here paths are passed to shell commands, so the "cmd.exe" quoting step must be unnecessary. I'll fix this and add more tests cases with strange paths to run on Windows via appveyor.

(Just in case, this bug doesn't affect luacheck at all if Luafilesystem is available, or when using the static luacheck binary)
