### ISSUE TITLE
Report syntax error messages

### ISSUE THREAD

**Issue by ignacio** [mpeterv/luacheck#17]
It would be nice to report the error message and its line when the file being checked has a syntax error. So, instead of just this:

~~~~
Checking d:\run.lua Syntax error
~~~~

We get something like what we have with luac
~~~~
luac: d:\run.lua:11: '=' expected near 'foo'
~~~~

I use luacheck with ST3. More than often, I make a syntax error and luacheck stops parsing the file I'm working on. Since I have no indication, I have no idea something is broken somewhere.

Thanks in advance!

**Comment by mpeterv** [comment]
I agree that this would be nice. I'll look into implementing this in another version but IMO this is not critical as there are already syntax-checking linters for Lua using `luac -p` for most editors, e.g. https://github.com/SublimeLinter/SublimeLinter-lua for ST3. So, it should be possible to configure it to run both `luac -p` and `luacheck`, or maybe installing them both is enough.

**Comment by ignacio** [comment]
Oh, I see. I thought it was a matter of just calling loadstring somewhere and dealing with that before starting to parse. But yeah, installing SublimeLinter-lua did the trick.

Thanks! (Feel free to close this if you want).

**Comment by mpeterv** [comment]
It is not that simple because of forward-compatibility, e.g. it should be possible to check Lua 5.3 code using bit operators while running on Lua 5.1. `loadstring` would then panic on a bit operator while an actual syntax error is still ahead. So, I would have to actually put some error reporting logic into the custom parser luacheck uses.

**Comment by mpeterv** [comment]
To be fixed in next version.

**Comment by mpeterv** [comment]
Fixed on master branch.

**Comment by ignacio** [comment]
Thank you. Works great
