### ISSUE TITLE
[W143] wrong field detection

### ISSUE THREAD

**Issue by cyw3** [mpeterv/luacheck#172]
`
local co_yield = coroutine._yield
`
[143] test.lua:13:18: accessing undefined field '_yield' of global 'coroutine'

I think it is a false alarm.

**Comment by mpeterv** [comment]
IIRC `coroutine._yield` is ngx_lua specific and not documented. Can use `read_globals` option to silence the warning: add `read_globals = {"coroutine._yield"}` to config (`.luacheckrc`), or pass `--read-globals coruotine._yield` on the command line, or put `-- luacheck: read globals coroutine._yield` before the line with the warning.
