### ISSUE TITLE
LuaChecks does not work with LuaRocks 3.0

### ISSUE THREAD

**Issue by helpermethod** [mpeterv/luacheck#176]
In LuaRocks 3.0, it's perfectly fine to leave of the build step in the rockspecs file

Example:
https://github.com/helpermethod/filenamify/blob/master/filenamify-dev-1.rockspec

The problem is that if I call luacheck with that said file then the following error will be emited

```
09:04 $ luacheck filenamify-dev-1.rockspec
/usr/local/bin/lua5.3: ...al/lib/luarocks/rocks-5.3/luacheck/0.22.1-1/bin/luacheck:2: module 'luacheck.main' not found
...
```

**Comment by mpeterv** [comment]
This error message is unrelated and indicates that the luacheck installation is somehow broken. Rockspecs without build table are indeed not supported:

```
Checking filenamify-dev-1.rockspec                Syntax error

    filenamify-dev-1.rockspec: rockspec.build is not a table

Total: 0 warnings / 0 errors in 0 files, couldn't check 1 file
```

Will fix.

**Comment by mpeterv** [comment]
Also `Syntax error` there is confusing, will change to `Format error`.

**Comment by mpeterv** [comment]
On master branch the error is gone, instead luacheck replicates module autodetection that Luarocks 3 performs.

**Comment by helpermethod** [comment]
Wow, that was fast! Thank you very much! And sorry for the useless error message, that was indeed a problem with my dev environment.
