### ISSUE TITLE
No executable when installing luacheck via npm on Mac OSX?

### ISSUE THREAD

**Issue by MartyMaro** [mpeterv/luacheck#179]
A Visual Studio extension requires luacheck to be a global executable command on my MacBook. I went ahead installing luacheck via `npm install -g luacheck`, but I don't get any bin link so I could use it on the Terminal and thus can be used by that extension. Instead all it does is installing the lib files so I can require luacheck within any JS app.

Is there a way to get it as executable on Mac OSX? I've seen there is only a bat file for Windows users. Any help is appreciated.

**Comment by mpeterv** [comment]
`luacheck` npm package is just a wrapper on top of luacheck CLI. Have you tried installing luacheck via [Luarocks](https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-macOS)? Either way, I'll try to make a static binary build for Mac OS.

**Comment by MartyMaro** [comment]
Thank you, how could I not think about LuaRocks. Works!

**Comment by ZanderDev** [comment]
Looking forward to a binary build for Mac OS.
