### ISSUE TITLE
Filtering out accessing undefined variable in luacheckrc 

### ISSUE THREAD

**Issue by SGTGunner** [mpeterv/luacheck#181]
I am getting this error -- `resources/Captain14_FBI/__resource.lua:1:1: accessing undefined variable resource_manifest_version` 

How do I filter out these errors in the luacheckrc file? I actually have a lot of variables that are valid in this case.

Thanks.

**Comment by mpeterv** [comment]
You can use `read_globals` option (use `globals` instead for globals that can be not just accessed but also set or mutated):

 ```lua
read_globals = {"resource_manifest_version", ...}
```

**Comment by SGTGunner** [comment]
Thanks. I added it to the `luacheckrc` file as `read_globals = {"resource_manifest_version"}`. And it did not help. Any other pointer to the problem?

**Comment by mpeterv** [comment]
The config file is `.luacheckrc`, with a dot in front.

**Comment by SGTGunner** [comment]
I am calling explicitly the configuration fire. But just to confirm I used `.luacheckrc` and tried the read_globals and it did not work. It did not exclude it.

**Comment by SGTGunner** [comment]
Thanks fixed it. It turned out how I was passing the configuration into luacheck.
