### ISSUE TITLE
Blacklist for some modules declared in global scope

### ISSUE THREAD

**Issue by keeprocking** [mpeterv/luacheck#184]
Hey Petya,

I need some kind of the opposite for read_globals option (i.e. the blacklist for the functions or modules that cannot be called from global scope) to make sure some specific functions/modules are required to local variables first.

A small example: with the config like

	no_read_globals = {'bar', 'baz'}

the following code

	foo()
	bar() -- warning
	baz() -- warning

should become something like this after refactoring:

	local bar = require 'bar'
	local baz = require 'baz'

	foo()
	bar()
	baz()

Is it possible to do with existing luacheck options? If not, could you please add such an option?

Thanks a lot.

**Comment by mpeterv** [comment]
Hello!

Does `not_globals = {'bar', 'baz'}` work for this usecase?
Does luacheck not warn about these globals by default?

**Comment by keeprocking** [comment]
Sorry for ambiguity, I mean something a bit different.
I want luacheck to raise warnings 113 for some specific cases only (when any of modules I specified in config are used) and ignore all other cases.
In other words, to get rid of these warnings one should rewrite this:

	require 'foo'
	require 'bar'
	require 'baz'

	foo()
	bar()
	baz()

with this:

	require 'foo'
	local bar = require 'bar'
	local baz = require 'baz'

	foo()
	bar()
	baz()

given the same config as in my previous message.

I'm not sure `not_globals` would work for this case.

**Comment by keeprocking** [comment]
Please disregard, this is not gonna work - I've actually came up with a more simple idea.
