### ISSUE TITLE
Walk directory tree looking for .luacheckrc

### ISSUE THREAD

**Issue by ignacio** [mpeterv/luacheck#20]
Basically, it would be really nice if Luacheck behaved like, for instance, JSHint.
Quoting from its docs:

> In case of .jshintrc, JSHint will start looking for this file in the same directory as the file that's being linted. If not found, it will move one level up the directory tree all the way up to the filesystem root.

Currently, I'm using Luacheck with Sublime.

**Comment by mpeterv** [comment]
Great idea, I look into implementing this. It shouldn't be too hard to do this even when luafilesystem is not available by using io.popen..

**Comment by ignacio** [comment]
Cool, thanks.

**Comment by mpeterv** [comment]
I implemented walking up from current directory in search of .luacheckrc on master branch. Per-file overrides are adjusted accordingly and should just work as if luacheck was run from the directory with the config. This is not exactly walking up from the directory in which checked file is located, but Sublime seems to change into that directory before running luacheck anyway, so it shouldn't matter.

**Comment by ignacio** [comment]
Just installed luacheck-scm with LuaRocks to test this, and it is working just fine. Thanks a lot.
