### ISSUE TITLE
Global being undefined

### ISSUE THREAD

**Issue by blasrodri** [mpeterv/luacheck#202]
First off, thanks for the amazing library @mpeterv!

```
std = {
globals = {"a", "b"}
}
```

I'd like this to fail, since we know that `b` is undefined.
```lua
a = 1
value = a * b
```

Performing the operating would give us somethign like:

```
stdin:1: attempt to perform arithmetic on a nil value (global 'b')
stack traceback:
	stdin:1: in main chunk
	[C]: in ?
```

**Comment by linuxmaniac** [comment]
please read https://github.com/mpeterv/luacheck/issues/198

**Comment by blasrodri** [comment]
@linuxmaniac Thanks. I'm sorry to read this.
