### ISSUE TITLE
Lua 5.4 support

### ISSUE THREAD

**Issue by alerque** [mpeterv/luacheck#203]
This project has an upper bound specified that is blocking usage on Lua 5.4. I kind of doubt there is any actual incompatibility and the version restriction can just be removed, but this needs to be tested and if it works a new rockspec released with a bumped rockrel that allows installation on Lua 5.4. Of course if there are other issues the code should be updated to work and a new full release is in order.

**Comment by linuxmaniac** [comment]
please read #198

**Comment by alerque** [comment]
Lua 5.4 is supported by the [new official repository](https://github.com/lunarmodules/luacheck) and latest releases.
