### ISSUE TITLE
Question: what are new_globals and new_read_globals?

### ISSUE THREAD

**Issue by idbrii** [mpeterv/luacheck#217]
[Custom sets of globals](https://luacheck.readthedocs.io/en/stable/config.html?#custom-sets-of-globals) describes globals and read_globals:

```lua
   globals = {"foo", "bar"}, -- these globals can be set and accessed.
   read_globals = {"baz", "quux"} -- these globals can only be accessed.
```

It later mentions the new_ variables:

> In config, globals, new_globals, read_globals, and new_read_globals can also contain definitions in same format:

But doesn't explain what they do.

I would guess these are their purpose:

*   globals -- these globals can be set and accessed.
*   read_globals -- these globals can only be accessed.
*   new_globals -- these globals can be set but not accessed.
*   new_read_globals -- these globals can be set and accessed.

However, that means globals and new_read_globals are the same. Possibly, "new_" means to append to another list -- use these globals in addition to std?

Also, [Config options](https://luacheck.readthedocs.io/en/stable/config.html?#config-options) says:

<html>
<body>

Option | Type | Default value
-- | -- | --
new_globals | Array of strings or field definition map | (Do not overwrite)
new_read_globals | Array of strings or field definition map | (Do not overwrite)

<br class="Apple-interchange-newline">
</body>
</html>

Which maybe means I shouldn't set the new_ variables? Why are they there?

**Comment by ur4ltz** [comment]
#198
