### ISSUE TITLE
Does Luacheck will work on 5.4?

### ISSUE THREAD

**Issue by asumbek** [mpeterv/luacheck#224]
Hello! I want to ask if Luacheck has support for Lua 5.4.

**Comment by alerque** [comment]
The original maintainer passed away (see #198). The community fork (as published on LuaRocks) is now [lunarmodules/luacheck](https://github.com/lunarmodules/luacheck), and yes it supports Lua 5.4. Please close this issue and switch to using that repository for any further issues.

**Comment by asumbek** [comment]
Rest in Peace, thank you for the information.
