### ISSUE TITLE
luacheck (on Linux Mint, at least) requires a rather old version of lua

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [mpeterv/luacheck#228]
It would be nice were luacheck - or at least the version of luacheck available in my distro's repository - able to use a version of lua newer than 5.1.

```
$ apt list lua5.* | grep installed

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

lua5.2/jammy,now 5.2.4-2 amd64 [installed,automatic]

$ sudo apt install lua-check
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  lua5.1
The following NEW packages will be installed
  lua-check lua5.1
```

My OS: Linux Mint 21 Vanessa (based on Ubuntu 22.04 Jammy).

**Comment by alerque** [comment]
The [current version of Luacheck](https://github.com/lunarmodules/luacheck/releases/tag/v1.0.0) can run on any Lua up to 5.4. How your distro packages it is up to the distro packagers, so you might have to take that up with Ubuntu by filing a bug against the package.

This repository is not the canonical one for Luacheck development. See #198 for the backstory, but [lunarmodules/luacheck](https://github.com/lunarmodules/luacheck) is not the canonical repository.

Please close this issue (as there is no-one else with access that can do so) and open any further issues on the current repository.
