### ISSUE TITLE
expression check

### ISSUE THREAD

**Issue by itldg** [mpeterv/luacheck#232]
My colleague wrote the following wrong code

I didn't realize the mistake at the time, just wanted to use it as a ternary expression.

The code execution will not report an error, but it will never get the desired result.

```lua
local a = bit.isset(data1, 0) and false or true
local b= bit.isset(data2, 7) and false or true
```

After the code was sent to me, I saw the code error prompt in VSCODE.

[Warn type:15], or expression is always true

[Warn type:16], and expression is always false

Can luacheck detect such errors?

**Comment by itldg** [comment]
I am deeply saddened to hear about his passing. He was an exceptional developer and an admirable individual. His contributions and talent will be forever remembered. May he rest in peace.

**Comment by alerque** [comment]
Please feel free to re-open this issue on the new canonical fork of this repository in the @lunarmodules org.

**Comment by alerque** [comment]
Never mind, it appears you did, it was just buried in my notifications.

https://github.com/lunarmodules/luacheck/issues/100
