### ISSUE TITLE
Print only warnings with specified numbers

### ISSUE THREAD

**Issue by CertHaramas** [mpeterv/luacheck#234]
Hello,
is there a way luacheck to print just "accessing undefined variable" and similar by-user-in-advance-specified warnings, nothing more?
My output is like:
"
    Abutment.lua:923:85: accessing undefined variable 'pln_70_L'
    Abutment.lua:928:85: accessing undefined variable 'pln_70_R'
    Abutment.lua:1226:1: line contains only whitespace
    Abutment.lua:1228:1: line contains only whitespace
    Abutment.lua:1709:9: empty if branch
    Abutment.lua:2059:6: accessing undefined variable 'z0'
"
In my situation, only lines:
"
    Abutment.lua:923:85: accessing undefined variable 'pln_70_L'
    Abutment.lua:928:85: accessing undefined variable 'pln_70_R'
    Abutment.lua:2059:6: accessing undefined variable 'z0'
"
should be printed, i.e. lines of warning number 111, 112 and 113:
"
111 Setting an undefined global variable.
112 Mutating an undefined global variable.
113 Accessing an undefined global variable.
"
TIA.
Best regards,
Lukas

**Comment by carrywang05** [comment]
您好，您的邮件我已经收到，谢谢！

**Comment by alerque** [comment]
Please close this issue since there is *nobody* with permissions to do so and this issue tracker is not maintained. See #198 for backstory. In the mean time you you have a question please open an issue on the [lunarmodules/luacheck](https://github.com/lunarmodules/luacheck) repo. Thanks.
