### ISSUE TITLE
Shameless plug; also pipe support?

### ISSUE THREAD

**Issue by za-creature** [mpeterv/luacheck#34]
Hey,

I've just written (technically forked then rewritten, but w/e) a [gulp plugin for luacheck](https://github.com/za-creature/gulp-luacheck). The package is [available on npm](https://www.npmjs.com/package/gulp-luacheck) so installing it should be a piece of cake. It depends on [the luacheck bindings for Node.JS](https://github.com/za-creature/node-luacheck), that I've also written and [published on npm](https://www.npmjs.com/package/luacheck). The separation is mostly there to allow for easier luacheck integration with other Node.JS build systems (such as Grunt)

While there hasn't been a lot of testing involved, I intend to maintain both packages in the foreseeable future, as I'm an avid Redis user and need them myself. Can you link to my two projects in luacheck's README?

Since this is technically an issue, is there any way to make luacheck read from stdin instead of a file?

**Comment by mpeterv** [comment]
Sure, I'll add both projects. As for checking stdin, pass `-` as argument, this should be mentioned in the docs.

**Comment by za-creature** [comment]
Awesome, thanks! I'll add pipe support in the next version.

Going to leave this open so you can close it when you've updated the docs about the stdin thing if that's alright with you.

Have a good one!

**Comment by za-creature** [comment]
My bad, it was there to begin with:

http://luacheck.readthedocs.org/cli.html?highlight=stdin
