### ISSUE TITLE
Confused about configuring Lua 5.3 *and* Busted globals in std option in .luacheckrc

### ISSUE THREAD

**Issue by kozross** [mpeterv/luacheck#35]
In short, how would I need to write my ``.luacheckrc`` if I wanted *both* the ``lua53`` and ``busted`` options to be set for ``std`` by default?

**Comment by mpeterv** [comment]
Globals can be merged using plus sign, so it should be `std = "lua53+busted"`. `std = "+busted"` should also work if you run luacheck using Lua 5.3 interpreter. Typically only files in `spec` directory need `busted` globals, in that case use an override:

```lua
std = "lua53"
files.spec.std = "+busted"
```

See docs: [[1]](http://luacheck.readthedocs.org/en/0.11.0/cli.html#sets-of-standard-globals) [[2]](http://luacheck.readthedocs.org/en/0.11.0/config.html#per-file-and-per-path-overrides).

**Comment by mpeterv** [comment]
@kozross does my comment solve this issue?

**Comment by kozross** [comment]
@mpeterv Yes, it does, thanks.
