### ISSUE TITLE
Cache makes line number mismatch

### ISSUE THREAD

**Issue by CheyiLin** [mpeterv/luacheck#37]
Hi,

I got mismatched line number (e.g., all shows `shadowing upvalue XXXX on line 7`) when enabling cache. Modifying Lua files or Recreating the cache will solve this issue temporarily.

Is it a caching bug?

**Comment by mpeterv** [comment]
Strange, can't reproduce this myself. So if you remove `.luacheckcache` and then run `luacheck` with `--cache` twice, do you get two different outputs?

**Comment by CheyiLin** [comment]
> if you remove .luacheckcache and then run luacheck with --cache twice, do you get two different outputs?

I got same output.

Maybe it was caused by `luacheck` upgrade? (from 0.11.0 to 56141edf0dd3eb7ad5cadd43374593c677ff71a9)

**Comment by mpeterv** [comment]
@CheyiLin probably, there was a fix related to caching. I'll add version number to cache to prevent this in the future.

**Comment by CheyiLin** [comment]
Got it, Thanks.
