### ISSUE TITLE
luacheck error when using a dirname

### ISSUE THREAD

**Issue by linuxmaniac** [mpeterv/luacheck#38]
This is using my luacheck 0.11.0-1 debian package version [0]
```
$ ls core/
s2scmanager.lua
$ luacheck core/
Checking core/                                    I/O error

Total: 0 warnings / 0 errors in 0 files, couldn't check 1 file
$ luacheck core/s2scmanager.lua 
Checking core/s2scmanager.lua                     11 warnings

    core/s2scmanager.lua:21:1: setting non-standard global variable incoming_s2sc
    core/s2scmanager.lua:22:25: accessing undefined variable incoming_s2sc
    core/s2scmanager.lua:23:23: accessing undefined variable incoming_s2sc
    core/s2scmanager.lua:28:10: setting non-standard global variable new_incoming
    core/s2scmanager.lua:35:10: setting non-standard global variable new_outgoing
    core/s2scmanager.lua:54:22: unused argument type
    core/s2scmanager.lua:57:10: setting non-standard global variable retire_session
    core/s2scmanager.lua:58:8: shadowing upvalue log on line 18
    core/s2scmanager.lua:72:10: setting non-standard global variable destroy_session
    core/s2scmanager.lua:96:2: accessing undefined variable retire_session
    core/s2scmanager.lua:100:8: accessing undefined variable _M

Total: 11 warnings / 0 errors in 1 file
```
[0] http://anonscm.debian.org/cgit/pkg-lua/lua-check.git

**Comment by mpeterv** [comment]
Do you have [LuaFileSystem](http://keplerproject.github.io/luafilesystem/) installed? It's required for expanding directories.

**Comment by linuxmaniac** [comment]
no, I missed that dependency. Do you have any more dependence?
Installing lua-filesystem fixes the issue. I will add that dependence to the package.

**Comment by mpeterv** [comment]
@linuxmaniac another dependency is [LuaLanes](http://cmr.github.io/lanes/), it's only required for multithreading (`-j` option) though.

**Comment by linuxmaniac** [comment]
OK, thanks. It seems LuaLanes is not yet packaged from Debian. I will try to take care of it.
Thanks!

**Comment by mpeterv** [comment]
@linuxmaniac how is the progress with the package? If I can do something to streamline it let me know.

**Comment by linuxmaniac** [comment]
Package waiting already for approval:
https://ftp-master.debian.org/new/luacheck_0.11.1+dfsg-1.html
