### ISSUE TITLE
Recursively check Lua files not ending in .lua

### ISSUE THREAD

**Issue by dirkfeytons** [mpeterv/luacheck#43]
I have a bunch of directories several levels deep that contain, among others, a bunch of Lua files but these files have a `.map` extension instead of `.lua`.
I can't seem to invoke luacheck to find and check these files. I tried a command line like `luacheck . --include-files **/*.map` but it doesn't find any file.

I had a look at the code in main.lua, more specifically `expand_files()`. When I specify a directory on the command line as a starting point (`.` in my example) then `fs.is_dir()` will be `true` and it will use `fs.extract_files(file, "%.lua$")` to find all filenames to check. I.e. only files ending in `.lua` will be found. The patterns given in `--exclude-files` and `--include-files` are only checked afterwards, in `add()`.

Is my use case indeed unsupported right now? Any suggestion?

**Comment by mpeterv** [comment]
@dirkfeytons so you propose that if `include-files` is used, it should override check for extension when recursing into directories? Seems reasonable. For now you can use `find` and `xargs`, e.g. `find -name '*.map' | xargs luacheck`.

**Comment by dirkfeytons** [comment]
@mpeterv: Yeah; I was kind of expecting that I could specify a directory to start from and that with `--include-files` I could specify which files to actually check.

I can let the shell do the globbing but it's a lot of files and I want to avoid hitting the limits of the amount of arguments I can pass. I want to do the checking with one invocation of luacheck so I have one JUnit test report covering everything. But I can work around it for now.

**Comment by mpeterv** [comment]
@dirkfeytons I've implemented this on master branch, can you check that it does what you want?

**Comment by mpeterv** [comment]
0.13.0 released with this fixed.

**Comment by dirkfeytons** [comment]
@mpeterv: now that the holiday period is over I finally got around to trying your change. I can confirm I can now easily do what I wanted; thanks!
