### ISSUE TITLE
Pattern match in per file overwrite.

### ISSUE THREAD

**Issue by xpol** [mpeterv/luacheck#52]
Can we have pattern (wildcard) match in per file config in .luacheckrc?

I want to do some overwrite for my rockspec files.
but the rockspec file name are keeps changing from release to release.

Shall we do the follow to disable global check for all rockspec files? 

```lua
--.luacheckrc
files['*.rockspec'].global = false
```

**Comment by mpeterv** [comment]
Yes, this should be rather easy to implement with globbing module already in place.

**Comment by mpeterv** [comment]
Implemented on master branch. I'll make a release today.

**Comment by xpol** [comment]
@mpeterv 
You are definitely awesome!
