### ISSUE TITLE
Recursive function calls

### ISSUE THREAD

**Issue by KillTheMule** [mpeterv/luacheck#60]
With the following file
```

local f = function(x)
  if not x.y then
    print(x)
  else
    f(x.y)
  end
end

local t = {}
t.y = "test"

f(t)
```

luacheck returns 1 error for line 5 

> tmp.lua:5:5: accessing undefined variable f

DId I miss something, or is this just not supported by luacheck?

**Comment by mpeterv** [comment]
This behavior is correct, in `local f = function() ... end` variable `f` enters scope only after right hand side is evaluated, so that inside the function `f` is global. This results in an error if you try to run this snippet:

```
lua: test.lua:5: attempt to call a nil value (global 'f')
stack traceback:
        test.lua:5: in local 'f'
        test.lua:12: in main chunk
        [C]: in ?
```

**Comment by KillTheMule** [comment]
Ah ok, you're right, but that was me trying to be smart and find a simple example... could you have a look at https://github.com/neovim/neovim/blob/master/test/unit/eval/helpers.lua#L29? That's where luacheck complains about the undefined variable "list", but shouldn't imho.

**Comment by mpeterv** [comment]
It's the same, the function is broken and will error if the branch with the "recursive" call is hit, unless `list` happens to be an existing global function. You should replace `local list = function(...)` with `local function list(...)` or `local list; list = function(...)`.

**Comment by KillTheMule** [comment]
Wow, I couldn't imagine that this is an issue of "dead" code... thanks a lot!

**Comment by mpeterv** [comment]
No problem, glad that luacheck helps!
