### ISSUE TITLE
luacheck crashes with latest LuaJIT 2.1 (287a534)

### ISSUE THREAD

**Issue by starius** [mpeterv/luacheck#67]
See https://github.com/LuaJIT/LuaJIT/issues/193#issuecomment-228578366

**Comment by mpeterv** [comment]
Yes, saw it [here](https://github.com/bluebird75/luaunit/pull/54#issuecomment-224382785). I've bisected and it is indeed introduced in a657fa0. I don't have a nice reduced example either though.

BTW, to install LuaJIT 2.1 from master using latest hererocks you need `-j @v2.1`, not `-j 2.1`. Or `-j @a657fa0` to install the commit that causes the trouble.

**Comment by mpeterv** [comment]
Fixed in LuaJIT.
