### ISSUE TITLE
Does `--filename` needs to be relative path to `.luachekrc`?

### ISSUE THREAD

**Issue by ghprince** [mpeterv/luacheck#68]
Hi, I am trying to fix luacheck on Emacs flycheck in this [PR](https://github.com/flycheck/flycheck/pull/1047)

And I wanna confirm that when luacheck reads data from stdin, if we want the following config to work

```lua
files['spec'] = { std = '+busted' }
```

we need to pass the **relative path** of the target file to `--filename` option.

If yes, can you help to leave a comment in that PR, so that I can get `flycheck` author's help to fix the issue?

**Comment by mpeterv** [comment]
Hi,

luacheck detects the config by iterating from current directory up to filesystem root, looking for config from each directory using path passed using `--config` or default `.luacheckrc`. All paths inside a config are then adjusted as if luacheck was run from the directory the config was found from. As an effect, if `--config` is used with direct path to config, paths are not adjusted at all, and it's necessary to pass relative path from actual project root to the checked file using `--filename`.

So, it's better to avoid using `--config` and let config detection do its thing. To ensure that it works start luacheck from the directory containing the checked file.

**Comment by ghprince** [comment]
@mpeterv Thanks a lot for your clear explanation, it's very helpful. The issue on Flycheck side is now fixed, so I am closing this issue too :)
