### ISSUE TITLE
disable standard globals

### ISSUE THREAD

**Issue by Tieske** [mpeterv/luacheck#69]
Is it possible to disable standard globals. Specifically I'd like to disable the length functions; `table.getn` and `string.len` to force using the operator `#`.

**Comment by mpeterv** [comment]
Right now it's not possible to disable specific fields of globals. It will be in the next version, I plan to work on it in October.

**Comment by Tieske** [comment]
Thx. Consider this a feature request then 😄

**Comment by Tieske** [comment]
(or close if you feel that's more appropriate)

**Comment by mpeterv** [comment]
I'm slowly working on a way to fully describe which fields of globals are allowed and which are not, in config. But there should be a way to tweak this with inline options, too. Most likely `globals` option will be changed to accept fields, and there will also be `no-globals` or `not-globals` option to prohibit a field or a global. For instance, luarocks-3 wants to ensure that `require` isn't used after some initial part of each core module, and it could use `-- luacheck: no global require` to verify that.

**Comment by mpeterv** [comment]
On `dev` branch:

```lua
-- luacheck: std max, not globals string.len table.getn
table.insert() -- OK
table.getn() -- accessing undefined field 'getn' of global 'table'
string.find() -- OK
string.len() -- accessing undefined field 'len' of global 'string'
```

It's still possible to use `("foo"):len()` but detecting that in the general case requires type inference.

**Comment by mpeterv** [comment]
0.19.0 released.

**Comment by Tieske** [comment]
:+1:
