### ISSUE TITLE
Windows install failing

### ISSUE THREAD

**Issue by matjojo** [mpeterv/luacheck#70]
Trying to install this on windows fails for me:

What I have:

Lua installed from here: https://code.google.com/archive/p/luaforwindows/

With all the options selected to install, meaning I also have Rocks and within that Luafilessystem, Luasocket, Luazip and md5.

what I tried:

I first tried the top installation option. I selected the command and it did not work because $ is not a valid command, omitted that, it worked a bit, this was the output:

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>luarocks install luacheck
Installing http://luarocks.org/repositories/rocks/luacheck-0.15.1-1.src.rock...

Missing dependencies for luacheck:
luafilesystem >= 1.6.3

cl /MD /O2 -c -Fosrc/lfs.obj -IC:/Program Files (x86)/Lua/5.1/include src/lfs.c
'cl' is not recognized as an internal or external command,
operable program or batch file.

Error: Failed installing dependency: http://luarocks.org/repositories/rocks/luaf
ilesystem-1.6.3-2.src.rock - Build error: Failed compiling object src/lfs.obj

C:\WINDOWS\system32>

after that I used the second installation version:

downloaded it and executed the install.Lua using LUA.exe, a page popped up for a very slight moment. but then nothing.

tried install.bat, the same problem. it popped up, and then nothing.

so that's it, any idea what I might be doing wrong?

**Comment by mpeterv** [comment]
The `$` is just shell prompt, it's not a part of a command.

For the first part, apparently LuaForWindows installed LuaFileSystem incorrectly, and also Luarocks isn't configured to use a compiler. Do you have Visual Studio installed (with C/C++ components)?

For the manual installation, how exactly did you invoke the script? It may have succeeded. I'll check how to work around the pop-up.

**Comment by mpeterv** [comment]
I can't the pop-up issue on my Windows 10 installation. You can try to add ` >log 2>&1` to the command and then, after it, run `type log` to show its output. Or try prefixing the command with `cmd.exe /k ` or `cmd.exe /c `.

**Comment by matjojo** [comment]
> Do you have Visual Studio installed (with C/C++ components)?

No, I do not have visual studio installed.

> For the manual installation, how exactly did you invoke the script?

Right mouse click > open file with: Lua.exe
I also tried the batch file, this did the same as the above method.

I now used command:
`luarocks install luacheck >log 2>&1`
It took a while, but no direct output. then
`type log`
This was the output:

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\matth>luarocks install luacheck >log 2>&1

C:\Users\matth>type log
'cl' is not recognized as an internal or external command,
operable program or batch file.
Installing http://luarocks.org/repositories/rocks/luacheck-0.15.1-1.src.rock...

Missing dependencies for luacheck:
luafilesystem >= 1.6.3

cl /MD /O2 -c -Fosrc/lfs.obj -IC:/Program Files (x86)/Lua/5.1/include src/lfs.c

Error: Failed installing dependency: http://luarocks.org/repositories/rocks/luaf
ilesystem-1.6.3-2.src.rock - Build error: Failed compiling object src/lfs.obj

It seems like to me at fails at command `cl` but I don't know a lot about command-prompt commands.

Then I ran command:

`cmd.exe /k luarocks install luacheck`

output:

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cmd.exe /k luarocks install luacheck
Installing http://luarocks.org/repositories/rocks/luacheck-0.15.1-1.src.rock...

Missing dependencies for luacheck:
luafilesystem >= 1.6.3

cl /MD /O2 -c -Fosrc/lfs.obj -IC:/Program Files (x86)/Lua/5.1/include src/lfs.c
'cl' is not recognized as an internal or external command,
operable program or batch file.

Error: Failed installing dependency: http://luarocks.org/repositories/rocks/luaf
ilesystem-1.6.3-2.src.rock - Build error: Failed compiling object src/lfs.obj

C:\WINDOWS\system32>

Then I ran:

`cmd.exe /c luarocks install luacheck`

Output:

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cmd.exe /c luarocks install luacheck
Installing http://luarocks.org/repositories/rocks/luacheck-0.15.1-1.src.rock...

Missing dependencies for luacheck:
luafilesystem >= 1.6.3

cl /MD /O2 -c -Fosrc/lfs.obj -IC:/Program Files (x86)/Lua/5.1/include src/lfs.c
'cl' is not recognized as an internal or external command,
operable program or batch file.

Error: Failed installing dependency: http://luarocks.org/repositories/rocks/luaf
ilesystem-1.6.3-2.src.rock - Build error: Failed compiling object src/lfs.obj

C:\WINDOWS\system32>


seems to me like the same problem,but again I don't know a lot about command-prompt commands.

If you have any idea, or even another lua-installation that I should try I'd love to hear it.

**Comment by mpeterv** [comment]
Yes, `cl` is a part of visual studio. Without it you can't install luafilesystem, a dependency of luacheck. Luacheck can still work without it, try `luarocks install luacheck --deps-mode=none`, however, you won't be able to check whole directories.

Actually I referred to the manual installation command when I mentioned `>log 2>&1` and `cmd /k` methods. It should be executed from terminal as well, e.g. `lua.exe install.lua <path>`, where `<path>` is some directory, then you'll need to add `<path>/bin` to PATH environment variable.

> If you have any idea, or even another lua-installation that I should try I'd love to hear it.

There are alternatives for installing Lua/LuaRocks but they all require a compiler (visual studio or [mingw](http://www.mingw.org/).

**Comment by mpeterv** [comment]
@matjojo have you tried `luarocks install luacheck --deps-mode=none` or anything else?

**Comment by matjojo** [comment]
Yep, tried those first, still did not work with CL, after that I decided to compile the newest version of LUA, and that worked, but this tim luarocks failed to install and I gave up, hope to have better luck next time.
