### ISSUE TITLE
Luacheck cannot ignore “loop is executed at most once” warning

### ISSUE THREAD

**Issue by ZyX-I** [mpeterv/luacheck#71]
Consider the following file:

    -- luacheck: ignore
    for k, v in pairs({1}) do return v done

When run like

    luacheck <(echo $'-- luacheck: ignore\nfor k, v in pairs({1}) do return v end')

luacheck successfully ignores “unused loop variable k” warning (condition is present here just to show that `luacheck: ignore` somewhat works), but it fails to ignore “loop is executed at most once”.

---

I need such code for a function that gets first dictionary item and would rather not either desugarate loop syntax (this is 3 or 2 lines, but they are less obvious) or rewrite logic behind “pairs” (it is actually custom function which iterates over a C dictionary, not lua table, so I can rewrite it).

**Comment by mpeterv** [comment]
Thanks for the report! This is a bug in warning filtering, looks like it applies to all warnings not related to variables. It only affects inline `luacheck: ignore`, explicit filtering using warning code should work as a workaround: `luacheck: ignore 512`.

**Comment by mpeterv** [comment]
Fixed on master branch. I'll release a new version with the fix and some accumulated changes next week.

**Comment by mpeterv** [comment]
Actually, just released 0.16.0.
