### ISSUE TITLE
check for deprecated functions

### ISSUE THREAD

**Issue by johnfoconnor** [mpeterv/luacheck#82]
there are various deprecations between lua versions. Would be nice if this library could detect when deprecated functions are used. This would require the user to specify which version of lua to check against. Maybe we can leverage the existing tags used for globals?

e.g.
lua 5.1 deprecates "table.getn" and "table.setn" (see http://www.lua.org/manual/5.1/manual.html#7.2)

we would want to lint for these functions if the user specified a version >= lua51

**Comment by mpeterv** [comment]
This goes in line with #46 and #65. Basically, `--std=lua51c` will list `getn` and `setn` as allowed fields of `table`, but `--std=lua51` won't, just like currently `--std=lua52` doesn't allow `module()` but `--std=lua52c` does. Sorry for little progress on these issues.

**Comment by mpeterv** [comment]
On `dev` branch:

```lua
-- luacheck: push std lua51
print(table.setn) -- Warning: accessing undefined field 'setn' of global 'table'
print(table.insert)
-- luacheck: pop

-- luacheck: push std lua51c
print(table.setn)
print(table.insert)
-- luacheck: pop
```
