### ISSUE TITLE
Way to remove certain globals from allowed set

### ISSUE THREAD

**Issue by daurnimator** [mpeterv/luacheck#88]
e.g. I would like to be alerted if I use `print` from a module that shouldn't be doing output (usually a left over debug print)

**Comment by mpeterv** [comment]
This is like #69 but for "root" global variables only. I'll add `not globals` option so that `not_globals = {"print", "another_global"}` works and then extend it once accessing fields of globals is recognized so that `not_globals = {"print", "io.stdout"}` works to filter fields as well.

**Comment by mpeterv** [comment]
Implemented on master branch, try `not_globals = {"print"}` in config or `-- luacheck: not globals print` inline.
