### ISSUE TITLE
Allow indirectly mutating read-only global variable but not direct?

### ISSUE THREAD

**Issue by Zash** [mpeterv/luacheck#91]
Is it possible to allow indirect, but not direct, mutation of some global?

Consider a server having a global `server` table which contains a `sessions` field, where it keeps references to all its client sessions. Mutating the top level `server` table should not happen but in this case mutating the `sessions` table is acceptable. But since both cases trigger the same warning, with the same code, one would have to spread out in-line ignore instructions there. Is there any way to have this in `.luacheckrc`?

**Comment by mpeterv** [comment]
Currently it's not possible, but I'm working on fine-grained definitions for globals with fields. So, in the next version something like this will work:

```lua
read_globals = {
   server = {
      fields = {
         sessions = {read_only = false, other_fields = true},
         -- other fields...
      }
   },
   --- other globals...
}
```

Or inline options: `-- luacheck: read_globals server, globals server.sessions`.

**Comment by mpeterv** [comment]
On `dev` branch:

```
-- luacheck: read_globals server, globals server.sessions
server = "foo" -- setting read-only global variable 'server'
server.something = "bar" -- setting read-only field 'something' of global 'server'
server.sessions.something = "baz" -- OK
```

**Comment by mpeterv** [comment]
0.19.0 released.
