### ISSUE TITLE
accessing undefined variable 'ngx'

### ISSUE THREAD

**Issue by cantoo** [mpeterv/luacheck#92]
Hi, 
I am using openresty, ngx is the framework inner variable, there's no need to define.
I add 'ngx' to linters.luacheck.ignore in sublimelinter user setting file.
But there's still check error: "accessing undefined variable 'ngx'"

**Comment by cantoo** [comment]
The error seems come out since upgrade to luacheck v2.0.0

**Comment by mpeterv** [comment]
Instead of using very limited editor-specific configuration, write [a luacheck configuration file](https://luacheck.readthedocs.io/en/stable/config.html). In your case, just put `std = ngx_lua` into a file named `.luacheckrc` in the root directory of your project.
