### ISSUE TITLE
Adding an error code for no errors and some warnings

### ISSUE THREAD

**Issue by argentum47** [mpeterv/luacheck#94]
Hello,

So I was writing a Makefile, which does a luacheck as a step. but the luacheck returns an exit code of 1 or 2 when there are some warnings involved along with other things . which makes my make <step> fail.

Which is totally not required, also I neither want to suppress the warnings nor do a || true . Just log the warnings and moove along .. 

So I was thinking of having a flag .. which would return an exit code of 4 or anything else when there are warnings. and based on that I can actually check in the Makefile / bash srcipt and return true or exit(0) .. or even like if the flag is present .. then return an exit code of 0 anyway..but log the warnings,

I can create a PR for this as well. Makes life easier

**Comment by mpeterv** [comment]
Hello,

So, currently exit codes are:

* 0 for OK
* 1 for warnings or (syntax) errors
* 2 for errors that shouldn't really be ignored: I/O (input files not found) and failure to load input files from a rockspec
* 3 for crashes, failure to load config.

We could make error code of `1` stand for just warnings and `2` stand for syntax errors and increment the other two codes. IIRC only vim plugin for luacheck relies on exit codes but it just checks that the code is less than 3, so this change shouldn't break it. What do you think?
