### ISSUE TITLE
Max line length warning code missing from documentation

### ISSUE THREAD

**Issue by Veratil** [mpeterv/luacheck#98]
The [current documentation](https://luacheck.readthedocs.io/en/stable/warnings.html) is missing [code 631 for max line length](https://github.com/mpeterv/luacheck/blob/master/src/luacheck/format.lua#L93).

**Comment by mpeterv** [comment]
My bad, thanks for noticing! I've added it on master branch. I'll wait for any other issues and release 0.19.1 next week.
